on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{secrets.SECRET_GITHUB_TOKEN}}
